pep_version: 2.0.0
sample_table: bedbuncher_query.csv
looper:
  run:
    output-dir: $BBTUTORIAL/outputs/bedbuncher_output/bedbuncher_pipeline_logs

sample_modifiers:
  append:
    pipeline_interfaces: $BBTUTORIAL/bedbuncher/pipeline_interface.yaml 
  derive:
    attributes: [JSONquery_path, bbconfig_path]
    sources:
      source1: $BBTUTORIAL/bedbuncher/tests/{JSONquery_name}.json
      source2: $BBTUTORIAL/configuration_files/{bbconfig_name}.yaml