name: Build and push dev image to Dockerhub

on:
  push:
    branches: [dev]
  workflow_dispatch:
    inputs: null   
    
jobs:
  dev-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout bedhost
      uses: actions/checkout@v4

    - name: Push to DockerHub
      uses: docker/build-push-action@v1
      with:
        dockerfile: ./dev.Dockerfile
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: databio/bedhost
        tag_with_ref: true
