name: Build and push dev image to Dockerhub

on:
  workflow_dispatch:
    inputs: null   
    
jobs:
  dev-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout bedhost
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to DockerHub
      uses: docker/build-push-action@v5
      with:
        file: ./dev.Dockerfile
        push: true
        tags: "databio/bedhost:dev"
