name: Build and push master image to Dockerhub

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: null   
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout bedhost repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: 
        - databio/bedhost:latest
        - databio/bedhost:${{github.ref_name}}

